[tools]
neovim = "0.11.4"
node = "24.9.0"
python = "3.14.0"
go = "1.25.2"
java = "25.0.0"
uv = "0.9.1"
usage = "2.3.2"

[settings]
experimental = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = []
