[tools]
neovim = "0.11.5"
node = "24.11.1"
go = "1.25.5"
java = "25.0.1"
uv = "0.9.15"
usage = "2.9.0"
protoc = "33.1"
bun = "1.3.3"
terraform-docs = "0.20.0"

[settings]
experimental = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = []
